version: '2.1'

services:
  
  database:
    image: mysql:5.7
    ports: 
      - '3306:3306'
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: 'YourPassWord'
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: YourPassWord

  wordpress:
    image: chenle/word-press
    ports: 
      - '80:80'
    depends_on:
      - database
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: 'YourPassWord'
